### PR TITLE
Fix sedona data folder structure

### PR DESCRIPTION
**Pull request by AndreySV**

### CODE REVIEW

**Comment by AndreySV** [comment]
First not all built files are placed currently into build directory. lib, bin, platforms/db, apps, scode contain compilation results as well. Therefore in my workflow I have special scripts that automate my daily tasks: build, clean, test, release.
This move brings more problems than benefits IMHO.
The major problem is that this move breaks default sedona data folder structure expected by existing programming tools. What programming tool do you use for sedona?
[commit message](https://github.com/linsong/sedona/pull/31/commits/88de6d873063b8a5860d21b688737d18b4156cf2) contains pretty detailed explanation of problems related to that move.

**Comment by linsong** [comment]
it's my fault, I missed your detailed commit message. Agreed with you that we should not break developer's sedona setup without strong reason. 

@divisuals , do you have any comment on this ?

**Comment by divisuals** [comment]
> @divisuals , do you have any comment on this ?

If the older tools are breaking as a result, then it is worth considering this change (moving away from build folder). Let me ask: any possibility of fixing those tools instead? 

It is good practice to keep all generated artifacts separate from source, which is why these changes were experimented. We can make a case for moving those generated artifacts (bin, lib, plat, scode, etc) in the build directory as well!

A lot of these directory settings are littered all over the code (discovered a few while moving docs from html to markdown). The long-term (durable) solution is to have all of these settings as options in python (or in a properties file for java), and just have the *default config* to support old tools, if you want.

**Comment by linsong** [comment]
Ok, I prefer to revert back to the old way based on following reasons: 
  1. The current change isn’t complete if considering use *build* folder as a Sedona data folder, and it will take sometime to make the switch. Reverting back to the old way is much easier. 
  2. We will need to document it very well to let others know why the old way does not work anymore, I guess probably many existing Sedona users will be confused at first since they may not read the document. 

I agree that putting all compiled files under *build* folder will be more clean. We can create a task to do it later and do all the required changes once(kits, manifests, bin, app, scode, documents etc). 

If there is no other comments, I will merge this PR in, thanks.

**Pull request merged**
