### PR TITLE
sys improvements

### PR DESCRIPTION
**Pull request by AndreySV**

### CODE REVIEW

**Comment by linsong** [comment]
@AndreySV I just reviewed your changes, they look good. I have some idea to improve it to make the name length change more smooth. I committed 2 changesets(more details in the commit comment). Please have a look.

**Comment by linsong** [comment]
Oops, there are some test broken, I will take a look shortly.

**Comment by linsong** [comment]
> That looks bad. You are changing communication protocol. Will be other tools aware of that? Will it break existing tools?

The header field is designed to be extended in backward compatible way. In SoxSession.sedona file, between line 157 ~ 168, the header's number is coded in the packet. For a decent implementation of programming tool, it should not depends on the number and order of headers here, and should skip the unknown header. 

So I think the programming tool should all support this, otherwise that should be thought of a defect. I just tested against CPT Tools since I only use it for work, but I believe Workbench and SAE should work, too. 

I added this because we need a way to pass the component name length information to programming tool at the beginning of a session, the header in 'welcome' message, the last message in handshake seems a good fit for me.

Just give it another thought, another place to pass this information is 'versionMore' command of Sox, and Sox is more related to component framework than Dasp.

**Comment by AndreySV** [comment]
> If 31chars version read 7chars version, that’s ok;but if the reversed case, only the first 7 chars are fetched from stream, the remaining chars will be parsed as other data, that will be wrong. It may happen since user can upload a single app.sab in programming tool, that may cause app.sab and kits.scode don’t match.

1. If names are too long for 7 characters, app will not be loaded. loadApp will return Err.nameTooLong. [See Component.sedona](https://github.com/linsong/sedona/blob/develop/src/kits/sys/Component.sedona#L420). No data will be overwritten.
2. If app.sab and kits.scode don't match, then app will not be loaded. sab file contains kits with required checksums. So they don't match, then app isn't loaded with error: "Schema mismatch (checksum): ...". [See App.sedona](https://github.com/linsong/sedona/blob/develop/src/kits/sys/App.sedona#L979).

**Comment by AndreySV** [comment]
I fixed problem, why tests failed. But this is exactly what I was afraid of. All tools that are using Tridium's sox JAVA implementation (or based on that) may just not work with newer sox kit.

Second question. Are you sure, that no other Sedona vendor is using ID for COMP_NAME_LEN?

**Comment by AndreySV** [comment]
Another potential problem is that sox is separate kit from sys. It's weakly bound to sys kit. It's possible to use new sox kit and old sys kit, that don't have Comp.nameLen. It'd potentially crash. To fix this we probably have to increase sys kit version and set corresponding version dependency for sox kit.

Better approach would be probably to add hidden read-only slot to PlatformService (in the same sys kit) with information about component's name length. What do you think?

**Comment by linsong** [comment]
> > If 31chars version read 7chars version, that’s ok;but if the reversed case, only the first 7 chars are fetched from stream, the remaining chars will be parsed as other data, that will be wrong. It may happen since user can upload a single app.sab in programming tool, that may cause app.sab and kits.scode don’t match.
> 
> 1. If names are too long for 7 characters, app will not be loaded. loadApp will return Err.nameTooLong. [See Component.sedona](https://github.com/linsong/sedona/blob/develop/src/kits/sys/Component.sedona#L420). No data will be overwritten.
> 2. If app.sab and kits.scode don't match, then app will not be loaded. sab file contains kits with required checksums. So they don't match, then app isn't loaded with error: "Schema mismatch (checksum): ...". [See App.sedona](https://github.com/linsong/sedona/blob/develop/src/kits/sys/App.sedona#L979).

**Comment by linsong** [comment]
> 1. If names are too long for 7 characters, app will not be loaded. loadApp will return Err.nameTooLong. [See Component.sedona](https://github.com/linsong/sedona/blob/develop/src/kits/sys/Component.sedona#L420). No data will be overwritten.
Yeah, you are right. My mistake, this is the main reason why I bump the app version, I will revert the version bump commit then.

**Comment by linsong** [comment]
> I fixed problem, why tests failed. But this is exactly what I was afraid of. All tools that are using Tridium's sox JAVA implementation (or based on that) may just not work with newer sox kit.

Yeah this is true. But I think we still need to pass the component name length limit to programming tool someway (in dasp header, sox header, or some other way), otherwise these programming tool has no chance to support longer component name. 

The good part is this is a just a simple fix/improvement.
 
> Second question. Are you sure, that no other Sedona vendor is using ID for COMP_NAME_LEN?

I am not sure, and it is hard to make sure for this. Since there should be several companies are maintaining their own sedona version, there is no central organization/company to manage this kind of thing. This issue should be solved when there is a main sedona fork others follows.

**Comment by linsong** [comment]
> Another potential problem is that sox is separate kit from sys. It's weakly bound to sys kit. It's possible to use new sox kit and old sys kit, that don't have Comp.nameLen. It'd potentially crash. To fix this we probably have to increase sys kit version and set corresponding version dependency for sox kit.

Yeah, I think we should increase the version of sys kit, since the function of sys kit has been updated, although its manifest interface still the same, the checksum should still be the same. 

> 
> Better approach would be probably to add hidden read-only slot to PlatformService (in the same sys kit) with information about component's name length. What do you think?

It's an option. One thing I am worried about is manifest files are separated from running app, they might be out of sync with the kit in running app. 
If we put the data into manifest, maybe we should create a new LimitService type object for this ? In my understanding, platform is more about the operation system, and a new LimitService can contain more limit data(how many kits can be installed, how many component objects can be created etc) in future.

There is another option: how about we extend the Sox protocol to add a new command to pass these kind of limits ? For example: 
```
req
{
  u1    'x'
  u1    replyNum
}
res
{
  u1   'X'
  u1   replyNum
  u1   limitCount
  limits[]
  {
    str  name
    str  value
  }
}
```
Any comments ?

**Comment by AndreySV** [comment]
> > I fixed problem, why tests failed. But this is exactly what I was afraid of. All tools that are using Tridium's sox JAVA implementation (or based on that) may just not work with newer sox kit.
> 
> Yeah this is true. But I think we still need to pass the component name length limit to programming tool someway (in dasp header, sox header, or some other way), otherwise these programming tool has no chance to support longer component name.

Even without 

> > 1. If names are too long for 7 characters, app will not be loaded. loadApp will return Err.nameTooLong. [See Component.sedona](https://github.com/linsong/sedona/blob/develop/src/kits/sys/Component.sedona#L420). No data will be overwritten.
> 
> Yeah, you are right. My mistake, this is the main reason why I bump the app version, I will revert the version bump commit then.

Thanks, simple drop of the corresponding commit would be enough. I've dropped both commits.

**Comment by AndreySV** [comment]
> > Better approach would be probably to add hidden read-only slot to PlatformService (in the same sys kit) with information about component's name length. What do you think?
> 
> It's an option. One thing I am worried about is manifest files are separated from running app, they might be out of sync with the kit in running app.

IMHO, it's essential that manifest **are in-sync** with kits in running app. Otherwise programming tool can't get slot names via sox protocol. AFAIK over sox only slot ids are transferred to make protocol very lightweight.

> If we put the data into manifest, maybe we should create a new LimitService type object for this ? In my understanding, platform is more about the operation system, and a new LimitService can contain more limit data(how many kits can be installed, how many component objects can be created etc) in future.

I've picked PlatformService because of following reasons:
1. it's included in the same Sys kit as Component and therefore it's not possible to change Components name without changing PlatformService.
2. Every App must contain PlatformService and easy to check by programming tool.
3. it's not necessary for that to change protocol or introduce any new formats/versions.

> There is another option: how about we extend the Sox protocol to add a new command to pass these kind of limits ? For example:
> 
> ```
> req
> {
>   u1    'x'
>   u1    replyNum
> }
> res
> {
>   u1   'X'
>   u1   replyNum
>   u1   limitCount
>   limits[]
>   {
>     str  name
>     str  value
>   }
> }
> ```
> 
> Any comments ?

I'd like to avoid changing protocol without strong reason.

**Comment by AndreySV** [comment]
Minimal working app and kits.scode:

```
<?xml version='1.0'?>
<sedonaApp>
<schema>
  <kit name="sys" />
  <kit name="sox" />
</schema>
<app>
  <prop name="appName" val="demo"/>
  <!-- /service -->
  <comp name="service" id="1" type="sys::Folder">
    <prop name="meta" val="33685505"/>
    <!-- /service/plat -->
    <comp name="plat" id="9" type="sys::PlatformService"/>
    <!-- /service/users -->
    <comp name="users" id="3" type="sys::UserService">
      <prop name="meta" val="17367041"/>
      <!-- /service/users/admin -->
      <comp name="admin" id="4" type="sys::User">
        <prop name="cred" val="hE49ksThgAeLkWB3NUU1NWeDO54="/>
        <prop name="perm" val="2147483647"/>
        <prop name="prov" val="255"/>
      </comp>
    </comp>
    <!-- /service/sox -->
    <comp name="sox" id="5" type="sox::SoxService">
      <prop name="meta" val="17104897"/>
    </comp>
  </comp>
</app>
<links>
</links>
</sedonaApp>

```


```
<!--
  -  Sedona SCode manifest for a generic unix platform
  -->

<sedonaCode
   endian="little"
   blockSize="4"
   refSize="4"
   main="sys::Sys.main"
   debug="true"
   test="true"
>

  <!-- Kits -->
  <depend on="sys 1.2" />
  <depend on="sox 1.2" />
  <depend on="inet 1.2" />
</sedonaCode>

```

**Pull request closed without merging**
